#!/bin/bash
##reference all arguments with  $@
##refernce number of arguments with $#

#number of arguments sent to the SSH command 
#(number of arguments before we need to insert singularity commands)
NUM_ARG_SSH=2

#which singularity image are we loading
SINGULARITY_IMAGE=/data/singularity/starccm.img

#TODO: this is currently pseudo-code, rewrite correctly
NEW_ARGUMENTS=$(sed $@ 's/ -n / -n singularity exec \/data\/singularity\/starccm\.img /g' )

ssh $NEW_ARGUMENTS

exit
